# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/nisitha/My_Passport/image_processing/image_processing.srcs/sources_1/bd/bd_img_proc_test/ip/bd_img_proc_test_auto_us_1/bd_img_proc_test_auto_us_1.xci
# IP: The module: 'bd_img_proc_test_auto_us_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/nisitha/My_Passport/image_processing/image_processing.gen/sources_1/bd/bd_img_proc_test/ip/bd_img_proc_test_auto_us_1/bd_img_proc_test_auto_us_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_img_proc_test_auto_us_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /media/nisitha/My_Passport/image_processing/image_processing.gen/sources_1/bd/bd_img_proc_test/ip/bd_img_proc_test_auto_us_1/bd_img_proc_test_auto_us_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_img_proc_test_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /media/nisitha/My_Passport/image_processing/image_processing.srcs/sources_1/bd/bd_img_proc_test/ip/bd_img_proc_test_auto_us_1/bd_img_proc_test_auto_us_1.xci
# IP: The module: 'bd_img_proc_test_auto_us_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/nisitha/My_Passport/image_processing/image_processing.gen/sources_1/bd/bd_img_proc_test/ip/bd_img_proc_test_auto_us_1/bd_img_proc_test_auto_us_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_img_proc_test_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /media/nisitha/My_Passport/image_processing/image_processing.gen/sources_1/bd/bd_img_proc_test/ip/bd_img_proc_test_auto_us_1/bd_img_proc_test_auto_us_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_img_proc_test_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
