# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/nisitha/My_Passport/image_processing/image_processing.srcs/sources_1/bd/bd_img_proc_test/ip/bd_img_proc_test_top_image_process_0_0/bd_img_proc_test_top_image_process_0_0.xci
# IP: The module: 'bd_img_proc_test_top_image_process_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /media/nisitha/My_Passport/image_processing/image_processing.srcs/sources_1/ip/output_buffer/output_buffer.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==output_buffer || ORIG_REF_NAME==output_buffer} -quiet] -quiet

# XDC: /media/nisitha/My_Passport/image_processing/image_processing.gen/sources_1/bd/bd_img_proc_test/ip/bd_img_proc_test_top_image_process_0_0/bd_img_proc_test_top_image_process_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_img_proc_test_top_image_process_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /media/nisitha/My_Passport/image_processing/image_processing.srcs/sources_1/bd/bd_img_proc_test/ip/bd_img_proc_test_top_image_process_0_0/bd_img_proc_test_top_image_process_0_0.xci
# IP: The module: 'bd_img_proc_test_top_image_process_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /media/nisitha/My_Passport/image_processing/image_processing.srcs/sources_1/ip/output_buffer/output_buffer.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==output_buffer || ORIG_REF_NAME==output_buffer} -quiet] -quiet

# XDC: /media/nisitha/My_Passport/image_processing/image_processing.gen/sources_1/bd/bd_img_proc_test/ip/bd_img_proc_test_top_image_process_0_0/bd_img_proc_test_top_image_process_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_img_proc_test_top_image_process_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
