webtalk_init -webtalk_dir D:/MOODLE/Vivado_projects/fpga_image_processing/image_processing/image_processing.sim/sim_1/behav/xsim/xsim.dir/tb_rgb_to_grayscale_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Jan  4 13:00:43 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212095426_0_0_145" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ad0c1586-c919-4d42-94ec-24af9a8ac574" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e4d4cc5ae4364d1eb999e599ac6e2b0b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "21" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 7535HS with Radeon Graphics        " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3294 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "7.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "30 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.67_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14456_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3205544753 -regid "212095426_0_0_145" -xml D:/MOODLE/Vivado_projects/fpga_image_processing/image_processing/image_processing.sim/sim_1/behav/xsim/xsim.dir/tb_rgb_to_grayscale_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/MOODLE/Vivado_projects/fpga_image_processing/image_processing/image_processing.sim/sim_1/behav/xsim/xsim.dir/tb_rgb_to_grayscale_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/MOODLE/Vivado_projects/fpga_image_processing/image_processing/image_processing.sim/sim_1/behav/xsim/xsim.dir/tb_rgb_to_grayscale_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
